services:
  opencloud:
    image: owncloud/ocis:latest
    container_name: opencloud

    user: "1000:1000"

    ports:
      - "9200:9200"

    environment:
      # URL pública EXACTA
      OCIS_URL: "https://26.195.60.25:9200"

      # importante para entornos sin certificados válidos
      OCIS_INSECURE: "true"

      # proxy
      PROXY_HTTP_ADDR: "0.0.0.0:9200"
      PROXY_TLS: "true"

      # rutas internas
      HOME: "/var/lib/ocis"
      OCIS_CONFIG_DIR: "/etc/ocis"

    volumes:
      - ./data/ocis:/var/lib/ocis
      - ./data/config:/etc/ocis

    command: server

    restart: unless-stopped

