services:
  opencloud:
    image: owncloud/ocis:latest
    container_name: opencloud
    ports:
      - "9200:9200"
    environment:
      OCIS_URL: "http://26.195.60.25:9200"
      OCIS_INSECURE: "true"
      OCIS_LOG_LEVEL: "info"
    volumes:
      - ./data:/var/lib/ocis
    restart: unless-stopped

