services:
  opencloud:
    image: owncloud/ocis:latest
    container_name: opencloud

    user: "1000:1000"

    ports:
      - "9200:9200"

    environment:
      OCIS_URL: https://26.195.60.25:9200
      OCIS_INSECURE: "true"

      PROXY_HTTP_ADDR: 0.0.0.0:9200

      HOME: /var/lib/ocis
      OCIS_CONFIG_DIR: /etc/ocis

    volumes:
      - ./data/ocis:/var/lib/ocis
      - ./data/config:/etc/ocis

    command: server

    restart: unless-stopped

