services:
  opencloud:
    image: owncloud/ocis:latest
    container_name: opencloud

    user: "1000:1000"

    ports:
      - "9200:9200"

    environment:
      OCIS_INSECURE: "true"
      OCIS_URL: "https://26.195.60.25:9200"
      HOME: "/var/lib/ocis"
      OCIS_CONFIG_DIR: "/etc/ocis"

    volumes:
      - ./data:/var/lib/ocis
      - ./data/config:/etc/ocis

    command: server

    restart: unless-stopped

